### PR TITLE
chore(datetime): migrate from moment to dayjs

### PR DESCRIPTION
**Pull request by DianaLease**
Signed-off-by: Diana Lease <dianarlease@gmail.com>

# Issue #205 

### Changes
-  Migrates concerto to use dayjs instead of moment due to the reasons described in #205 

### Flags
- We no longer preserve the timezone offset as we did with `Moment.parseZone()` bc dayjs does not offer equivalent functionality.
- Dayjs is less strict about what it will parse as a date. To combat this, this PR adds validation to check if the value is undefined or not a string in `serializer/objectvalidator.js`
- I'll keep this PR open to discuss on next weeks's WG call

### CODE REVIEW

**Review by mttrbrts — APPROVED** [review]
Good work, @DianaLease 👏 

Just one question on this statement:

> We no longer preserve the timezone offset as we did with Moment.parseZone() bc dayjs does not offer equivalent functionality.

Does this imply that all parent libraries will now become responsible for TZ / Offset normalization before using Concerto? If not, the Dayjs behaviour could cause errors where the offset is silently dropped (which actually changes the timestamp)?

**Comment by DianaLease** [comment]
> Does this imply that all parent libraries will now become responsible for TZ / Offset normalization before using Concerto? If not, the Dayjs behaviour could cause errors where the offset is silently dropped (which actually changes the timestamp)?

The offset will be used when it gets converted into utc, so the _actual_ time shouldn't change. However, once it's in utc, we won't have a way to know which timezone it was originally in when passed to dayjs.  (cc @jeromesimeon)

**Review by jeromesimeon — APPROVED** [review]
Looks great! Unless anybody has further objections, I would vote for merging this PR and make this switch to `day.js` part of the upcoming Concerto 1.0 release.

**Comment by jeromesimeon** [comment]
> > Does this imply that all parent libraries will now become responsible for TZ / Offset normalization before using Concerto? If not, the Dayjs behaviour could cause errors where the offset is silently dropped (which actually changes the timestamp)?
> 
> The offset will be used when it gets converted into utc, so the _actual_ time shouldn't change. However, once it's in utc, we won't have a way to know which timezone it was originally in when passed to dayjs. (cc @jeromesimeon)



> > Does this imply that all parent libraries will now become responsible for TZ / Offset normalization before using Concerto? If not, the Dayjs behaviour could cause errors where the offset is silently dropped (which actually changes the timestamp)?
> 
> The offset will be used when it gets converted into utc, so the _actual_ time shouldn't change. However, once it's in utc, we won't have a way to know which timezone it was originally in when passed to dayjs. (cc @jeromesimeon)

Couldn't have said it better.

**Pull request merged**
