### PR TITLE
(feat) typescript definitions

### PR DESCRIPTION
**Pull request by j4m3sb0mb**
Signed-off-by: Giacomo Minighin <giacomo.minighin@gmail.com>

### Changes
- created typescript definitions

### CODE REVIEW

**Comment by mttrbrts** [comment]
Nicely done, thanks @j4m3sb0mb!

**Comment by j4m3sb0mb** [comment]
I've followed your js-docs to create this, some of the functions were private and so I made them private as well in concerto-core types. do you think they should be public?

**Comment by mttrbrts** [comment]
I think that marking them private is the correct thing to do. If users want to extend a built-in class, then they should know that they can use private functions.

**Comment by jeromesimeon** [comment]
@mttrbrts @j4m3sb0mb How are those being tested? And somewhat related: what is the process to maintain them when the API changes?

**Comment by mttrbrts** [comment]
No tests at the moment, and maintained manually. 

I wonder if we could extend https://github.com/accordproject/concerto/blob/master/packages/concerto-core/lib/tools/versionchecker.js to do the check / hash? At the very least we know when the API changes already so we can warn people to update the `types/index.d.ts` file too.

**Comment by jeromesimeon** [comment]
@mttrbrts sounds like a good idea to start. Would you mind opening an issue for that?

**Pull request merged**
