### PR TITLE
Centering Concerto and badges 

### PR DESCRIPTION
**Pull request by DEBSUBHRO**
**Issue** #79
 
**Changes**
Centering the title and badges.
 
**Related Issues**
 
* Issue #79
* Pull Request #76

### CODE REVIEW

**Comment by DEBSUBHRO** [comment]
**Issue** #79
 
**Changes**
Centering the title and badges.
 
**Related Issues**
 
* Issue #79
* Pull Request #76

**Comment by mttrbrts** [comment]
Hi @DEBSUBHRO , thanks for you PR. Can you please add a DCO sign-off?

If you're making the change via the GitHub UI, simply add the signoff text in your comment. If may be easier for you to close this PR and make a new one if you're not familiar with the `git` command line tool yet.
```
Signed-off-by: Random J Developer <random@developer.example.org>
```

**Comment by DEBSUBHRO** [comment]
> Hi @DEBSUBHRO , thanks for you PR. Can you please add a DCO sign-off?
> 
> If you're making the change via the GitHub UI, simply add the signoff text in your comment. If may be easier for you to close this PR and make a new one if you're not familiar with the `git` command line tool yet.
> 
> ```
> Signed-off-by: Random J Developer <random@developer.example.org>
> ```

Yes, Sir. I am creating a new one. I apologize for the delay.

**Comment by jeromesimeon** [comment]
Done in PR #109

**Pull request closed without merging**
