### PR TITLE
feat(javaVisitor):used java.time.Instant instead of java.util.Date

### LINKED ISSUE #101: java.time.Instant rather than java.util.Date in the Java target format?
Is it recommended best practice to use Java.time rather than the older (and considered poorly designed) Java.util.date, as currently used by the `concerto-tools` Java target.

## Context

This isn't a bug, but a suggestion for improvement.

## Expected Behavior

CTO concepts making use of the `DateTime` atomic types should generate Java classes with fields using `java.time.Instant`.

## Actual Behavior

CTO concepts making use of the `DateTime` atomic types generate Java classes with fields using `java.util.Date`.

## Possible Fix

Maybe, just this line to change:https://github.com/accordproject/concerto/blob/58a322bf0541c2b5ccd68b60da674efe9f6a9a36/packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js#L364

### PR DESCRIPTION
**Pull request by Aniruddha-Shriwant**
Signed-off-by: Aniruddha Shriwant <aniruddhashriwant@gmail.com>

# Closes #101 <CORRESPONDING ISSUE NUMBER>

### Changes

- Changed `java.util.Date` with `java.time.Instant` 

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`

### CODE REVIEW

**Comment by Aniruddha-Shriwant** [comment]
Are test failing due to this code?
https://github.com/accordproject/concerto/blob/c2ecad3e5d52b0e8b1c7caf026d62abbf4f68b6f/packages/concerto-tools/test/codegen/fromcto/java/javavisitor.js#L677-L680

**Comment by Aniruddha-Shriwant** [comment]
> Are tests failing due to this?
> https://github.com/accordproject/concerto/blob/c2ecad3e5d52b0e8b1c7caf026d62abbf4f68b6f/packages/concerto-tools/test/codegen/fromcto/java/javavisitor.js#L677-L680

@jeromesimeon as this idea of java.time.Instant was suggested by you, Can you review this failing tests

**Comment by jeromesimeon** [comment]
@Aniruddha-Shriwant The tests are supposed to test the library, so it seems likely that your change would make the related tests fail.

**Comment by jeromesimeon** [comment]
@Aniruddha-Shriwant any update on this?

**Comment by Aniruddha-Shriwant** [comment]
> @Aniruddha-Shriwant any update on this?

So, Should I change these test from this:
https://github.com/accordproject/concerto/blob/c2ecad3e5d52b0e8b1c7caf026d62abbf4f68b6f/packages/concerto-tools/test/codegen/fromcto/java/javavisitor.js#L677-L680

to this: 
```
    describe('toJavaType', () => {
        it('should return java.util.Date for DateTime', () => {
            javaVisit.toJavaType('DateTime').should.deep.equal('java.time.Instant');
        });
``` 

Changing that won't pass the tests for this PR but future checks will pass...

**Comment by Aniruddha-Shriwant** [comment]
> Changing that won't pass the tests for this PR but future checks will pass...

@jeromesimeon I was wrong :) 
This works :)

**Pull request closed without merging**
