### PR TITLE
optimization of concerto parser

### PR DESCRIPTION
**Pull request by j4m3sb0mb**
# Issue #55
added optimize option to prepare script

### Changes
packages/concerto-core/package.json

### CODE REVIEW

**Comment by jeromesimeon** [comment]
> # Issue #55
> added optimize option to prepare script
> 
> ### Changes
> packages/concerto-core/package.json

Good catch! thanks @j4m3sb0mb I'll fix this ASAP.

**Comment by jeromesimeon** [comment]
That looks like a nice change to me. @mttrbrts ?

**Comment by dselman** [comment]
LGTM. I remember trying this in the past however and it made negligible difference to the size of the generated code once web packed.

**Comment by mttrbrts** [comment]
Closing given discussion on issue #55

**Pull request closed without merging**
