### PR TITLE
feat(vocabulary) : support multiple terms per concept/property

### LINKED ISSUE #645: Allow multiple vocabulary terms per concept and property
# Feature Request 🛍️

At present we only allow a single vocabulary term per concept and per concept property. It would be useful to expand this to support an unlimited set of terms.

## Use Case

Users often need to associate a short term, long term, tooltip, descriptive term etc. with the same property or concept.

### PR DESCRIPTION
**Pull request by dselman**
# Closes #645 

### Changes
- <ONE>
- <TWO>

### Flags

- <ONE>
- <TWO>

### Related Issues
- Issue #<NUMBER>
- Pull Request #<NUMBER>

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `main` from `fork:branchname`

### CODE REVIEW

**Comment by sanketshevkar** [comment]
Hi @dselman 
Here is the PR fixing the bug and I've new test cases.

**Comment by sanketshevkar** [comment]
@dselman I had to fix tests for the changes made, here is PR for that https://github.com/accordproject/concerto/pull/667
I had signed off the previous commits, but not sure why DCO check is failing.

**Comment by dselman** [comment]
> @dselman I had to fix tests for the changes made, here is PR for that #667
> I had signed off the previous commits, but not sure why DCO check is failing.

image

**Comment by dselman** [comment]
@sanketshevkar can you please resolve the merge conflicts?

**Review by mttrbrts — APPROVED** [review]

**Pull request merged**
