### PR TITLE
Centering Concerto and badges

### PR DESCRIPTION
**Pull request by DEBSUBHRO**
##Issue #79

##Changes
Centering the title and badges.

##Related Issues
Issue #79
Pull Request #76

### CODE REVIEW

**Comment by jeromesimeon** [comment]
This ended up being fixed when adding the code coverage badge.

**Comment by jeromesimeon** [comment]
Actually my apologies, the centering of the logo is still pending so I'm reopening this 😄

**Comment by DEBSUBHRO** [comment]
Sir, I have made the changes in PR #97. Please check it.
I also want to apologize for the fact I am could not "DCO signoff" to the PRs of AccordProject because I haven't installed git. I am learning about it and will do it as soon as possible. It will be a great help if you can merge it to the master branch.
Thank you.

**Comment by jeromesimeon** [comment]
> Sir, I have made the changes in PR #97. Please check it.
> I also want to apologize for the fact I am could not "DCO signoff" to the PRs of AccordProject because I haven't installed git. I am learning about it and will do it as soon as possible. It will be a great help if you can merge it to the master branch.
> Thank you.

Hi @DEBSUBHRO Thanks for your contribution. The DCO signoff is mandatory since it is a statement of originality for the open-source contribution. I am pretty sure you need git for that, but I could be wrong (it's possible that there is a GitHub way to do it, but I do not know for sure).

In case useful, there is some documentation about DCO Signoff here: https://github.com/apps/dco

**Comment by DEBSUBHRO** [comment]
> > Sir, I have made the changes in PR #97. Please check it.
> > I also want to apologize for the fact I am could not "DCO signoff" to the PRs of AccordProject because I haven't installed git. I am learning about it and will do it as soon as possible. It will be a great help if you can merge it to the master branch.
> > Thank you.
> 
> Hi @DEBSUBHRO Thanks for your contribution. The DCO signoff is mandatory since it is a statement of originality for the open-source contribution. I am pretty sure you need git for that, but I could be wrong (it's possible that there is a GitHub way to do it, but I do not know for sure).
> 
> In case useful, there is some documentation about DCO Signoff here: https://github.com/apps/dco

Thamk you, Sir. I will check it.

**Pull request closed without merging**
