### PR TITLE
feat: vocabulary manager

### LINKED ISSUE #360: Mechanism to define human-readable labels for model elements
# Feature Request 🛍️
For use cases that create user interfaces from models it is necessary to define human-readable labels for model elements (concepts and properties).

## Use Case
Provide a mechanism to define natural language labels for model elements, supporting a variety of locales.

## Possible Solutions
1. Define a standard set of decorators to capture labels. E.g. `@label("en", "My Fancy Concept")`
2. Define a sidecar **vocabulary** file to store labels outside of the model file. E.g.

org.acme_en.voc (a yaml file):

``` yaml
Address:      Street Address
properties:
    line1:    First line of street address
    line2:    Second line of street address
    city:     City or Town
    county:   County name
    state:    State or region name
    postCode: Postal or Zip code
    country:  Country code
```

## Context
This feature would be used by form generators as well as the parser generator (e.g. for enumerated values), allowing natural language labels to be used, rather than the technical model element names.

## Detailed Description

On balance I favour the sidecar yaml file proposal as it ensures that the model doesn't get cluttered with decorators, especially if the model needs to support multiple locales. The yaml file is also easier (and less risky) to send for translation to external translation companies.

We would need to add `VocabularyManager` API to load a set of `voc` files for a set of locales  and to validate them against the models (no extra keys), and add utilities to load the label for a given locale for a model element.

### PR DESCRIPTION
**Pull request by dselman**
Signed-off-by: Dan Selman <danscode@selman.org>

# Closes #360 

Adds a new package `concerto-vocabulary` to manage a set of terms that are defined for model elements.

### Changes
- Vocabulary Class
- Vocabulary Manager Class
- VocabularyManager.getTerm method will find the most specific term possible for a model element, searching locales from most specific to most general. E.g.` en-gb -> en`, or `fr-ca to fr`.
- VocabularyManager.validate method detects redundant or missing terms.
- VocabularyManager.resolveTerm to use the model manager type hierarchy to find a term
- VocabularyManager.englishMissingTermGenerator to generate terms in English from declaration and property name

### Flags
- Uses yaml serialisation for a vocabulary

### Example Model

```
namespace org.acme

enum Color {
    o RED
    o BLUE
    o GREEN
}

asset Vehicle identified by vin {
    o String vin
    o Color color
}
```

### Example Vocabulary Files

``` yaml
locale: en
namespace: org.acme
declarations:
  - Color: A color
  - Vehicle: A road vehicle
    properties:
      - vin: Vehicle Identification Number
      - model: Model of the vehicle
  - Truck: A vehicle capable of carrying cargo
```

``` yaml
locale: en-gb
namespace: org.acme
declarations:
  - Truck: A lorry (a vehicle capable of carrying cargo)
  - Color: A colour
```

```yaml
locale: fr
namespace: org.acme
declarations:
  - Vehicle: Véhicule
    properties:
      - vin: Le numéro d'identification du véhicule (NIV)
```

### Example API Usage

```
        const voc = vocabularyManager.getVocabulary('org.acme', 'en');
        voc.should.not.be.null;
        const term = voc.getTerm('Vehicle');
        term.should.equal('A road vehicle');
        const term2 = voc.getTerm('Vehicle', 'vin');
        term2.should.equal('Vehicle Identification Number');
```

```
        const result = vocabularyManager.validate(modelManager);
        result.missingVocabularies.length.should.equal(0);
        result.additionalVocabularies.length.should.equal(1);
        result.additionalVocabularies[0].getNamespace().should.equal('com.example');
        result.vocabularies['org.acme/en'].additionalTerms.should.have.members(['Vehicle.model', 'Truck']);
        result.vocabularies['org.acme/en'].missingTerms.should.have.members(['Color.RED', 'Color.BLUE', 'Color.GREEN', 'Vehicle.color']);
        result.vocabularies['org.acme/fr'].missingTerms.should.have.members(['Color', 'Vehicle.color']);
        result.vocabularies['org.acme/fr'].additionalTerms.should.have.members([]);
```

### Related Issues
- Issue #<NUMBER>
- Pull Request #<NUMBER>

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`

### CODE REVIEW

**Review by mttrbrts — APPROVED** [review]
Very nice!

A few questions about the syntax and extensibility....

If I wanted to add vocabulary for the Enum I would follow the same syntax as for Class declarations? e.g.

```
locale: fr
namespace: org.acme
declarations:
  - Color: Couleur
    properties:
      - BLUE: bleu
      - RED: rouge
      ...
```
      
  The syntax appears to be extensible to more advanced uses in the future for example....
  ```
locale: en
namespace: org.acme
declarations:
  - Vehicle: a vehicle
    description: a road vehicle
    properties:
      - vin: Vehicle Identification Number
        description: a unique identifier for the vehicle provided by the licensing authority
      ```
      
  Some questions, likely all future extenions:
  1. Have you thought about support for language subtags? e.g. `gsw-u-sd-chzh`
  2. I assume that this all works nicely with non-latin characters, i.e. when UTF-8 encoded? A test would be a helpful exemplar.

**Comment by dselman** [comment]
> Very nice!
> 
> A few questions about the syntax and extensibility....
> 
> If I wanted to add vocabulary for the Enum I would follow the same syntax as for Class declarations? e.g.
> 
> ```
> locale: fr
> namespace: org.acme
> declarations:
>   - Color: Couleur
>     properties:
>       - BLUE: bleu
>       - RED: rouge
>       ...
>       ```

Yes, that should work. I will add an enum example.

>       
>   The syntax appears to be extensible to more advanced uses in the future for example....
> ```
> 
> locale: en namespace: org.acme declarations:
> 
> * Vehicle: a vehicle
>   description: a road vehicle
>   properties:
>   
>   * vin: Vehicle Identification Number
>     description: a unique identifier for the vehicle provided by the licensing authority

Yes, that could be an interesting enhancement.

>   
>   ```
>   
>   ```
> 
> Some questions, likely all future extenions:
> 
> 1. Have you thought about support for language subtags? e.g. `gsw-u-sd-chzh`

That should work today, but it is "naive" in that it will merely walk up the hierarchy, splitting on `-`. This works for most languages, but not all. I tried to find a ["best match"](https://stackoverflow.com/questions/55089897/how-do-i-use-the-best-fit-locale-in-javascript) implementation In Javascript but didn't find one - I think the browsers must be using ICU native code. However, I think we can add this as an extensions - which is what the browsers also did.

> 2. I assume that this all works nicely with non-latin characters, i.e. when UTF-8 encoded? A test would be a helpful exemplar.

It should! I'd welcome a translation of the model for testing!

**Review by jeromesimeon — APPROVED** [review]
Really cool contribution

**Review by mttrbrts — APPROVED** [review]
✅ 

The missing term generator is nice, I wonder about extending it to formalise the magic that happens for labels in the form generator? 🤔

**Review by jeromesimeon — APPROVED** [review]
LGTM!

**Comment by mttrbrts** [comment]
> > ✅
> > The missing term generator is nice, I wonder about extending it to formalise the magic that happens for labels in the form generator? 🤔
> 
> Yes, that would be a great idea. I had a quick look at the code but didn't find the "magic" :-)

It's here: https://github.com/accordproject/web-components/blob/master/packages/ui-concerto/src/utilities.js#L20-L25

**Pull request merged**
