### PR TITLE
fix(core): private accept methods in introspect classes - I839

### LINKED ISSUE #839: Make `accept` methods of introspection classes public
Make `accept` methods of introspection classes public
# Feature Request 🛍️

Currently only the model manager class as a public `accept` method. However, if a detailed crawling on the syntax tree is required, then we might need to access `accept` methods of other introspection classes, like `ClassDeclaration` or `ModelFile`. However, all the those `accept` methods [are marked as private](https://github.com/accordproject/concerto/blob/main/packages/concerto-core/lib/introspect/modelfile.js#L188).

On top of all that, we are dismissing this in our own code generators, [like](https://github.com/accordproject/concerto-codegen/blob/a2463e0d7d0363653d9c195b80ab812d34a14692/lib/codegen/fromcto/rust/rustvisitor.js#L129) `RustVisitor`.

This is not a huge problem in JS, but in TypeScript, the types generated using the annotations raise compiler errors while trying to access private methods.

## Use Case

* Being able to refine the visitor.
* Our own code generation.

## Possible Solution

Marking those methods as public

## Context

* I'm trying to take advantage of internal machinery while flattening types and I wanted to use the visitor pattern.

### PR DESCRIPTION
**Pull request by apoorvsxna**
# Closes #839 

### Changes
- Edited JSDoc of `accept` methods in introspect classes to mark them as `public`.
- Does not change javascript functionality.
- Change is reflected in the generated typescript files in `lib/types`

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Merging to `main` from `fork:branchname`

### CODE REVIEW

**Comment by ekarademir** [comment]
Could you also run `npx lerna run build` and commit the changes please?

**Review by mttrbrts — CHANGES_REQUESTED** [review]
@apoorvsxna There's a build failure now that the API has changed. Please follow the instructions in the log to fix the api.txt file.

```
Error: Computed public API digest did not match the digest in the changelog for the most recent version. Increment the version number and add a new entry to the changelog (explaining your public API change) using the digest 56df3674b9e8d094cec0ae690c07ea1f. Run 'git diff api.txt' to understand the pubic API changes. Please ensure that TypeScript definitions are up to date by executing `npm run build:types`
```

**Comment by apoorvsxna** [comment]
> @apoorvsxna There's a build failure now that the API has changed. Please follow the instructions in the log to fix the api.txt file.
> 
> ```
> Error: Computed public API digest did not match the digest in the changelog for the most recent version. Increment the version number and add a new entry to the changelog (explaining your public API change) using the digest 56df3674b9e8d094cec0ae690c07ea1f. Run 'git diff api.txt' to understand the pubic API changes. Please ensure that TypeScript definitions are up to date by executing `npm run build:types`
> ```

Yes, I ran into this error when running the tests. I'll fix this and make a commit in a while.

**Comment by apoorvsxna** [comment]
I was running into a conflict when trying to update this pull request. I've addressed the requested changes and made a [new PR](https://github.com/accordproject/concerto/pull/843). Closing this PR now.

**Pull request closed without merging**
