### PR TITLE
Update package.json for the package name concerto-core

### PR DESCRIPTION
**Pull request by Niladri24dutta**
### Fixes issue #74 
Updated package name as `concerto-core` 

### Changes
- Updated package name as `concerto-core` to avoid confusion in npm, and align with other Accord Project .

### CODE REVIEW

**Comment by Niladri24dutta** [comment]
@jeromesimeon it seems there is a build issue in the travis pipeline. Can you let me know if I need to update the package name somewhere else as well?maybe the old name is still used by some other dependent packages.

**Comment by mttrbrts** [comment]
@Niladri24dutta you're exactly right, you should update the dependencies for `concerto-cli` and `concerto-tools` too. For example, https://github.com/accordproject/concerto/blob/master/packages/concerto-cli/package.json#L43

@jeromesimeon this is a breaking change so we should bump to `0.81.0` on the next release.

**Comment by Niladri24dutta** [comment]
> 
> 
> @Niladri24dutta you're exactly right, you should update the dependencies for `concerto-cli` and `concerto-tools` too. For example, https://github.com/accordproject/concerto/blob/master/packages/concerto-cli/package.json#L43
> 
> @jeromesimeon this is a breaking change so we should bump to `0.81.0` on the next release.

@mttrbrts 
Sure I will update the dependencies in `concerto-tools` package and others package.json if required. I was getting a strange issue in mocha during the test case execution so I updated the unit test cases as well. But still i think this packages needs to be renamed https://github.com/accordproject/concerto/blob/master/packages/concerto-cli/package.json#L48

**Comment by Niladri24dutta** [comment]
@mttrbrts  However regarding the version of `sinon` which you mentioned above. I believe it's same across all the tools.

**Comment by jeromesimeon** [comment]
> > @Niladri24dutta you're exactly right, you should update the dependencies for `concerto-cli` and `concerto-tools` too. For example, https://github.com/accordproject/concerto/blob/master/packages/concerto-cli/package.json#L43
> > @jeromesimeon this is a breaking change so we should bump to `0.81.0` on the next release.
> 
> @mttrbrts
> Sure I will update the dependencies in `concerto-tools` package and others package.json if required. I was getting a strange issue in mocha during the test case execution so I updated the unit test cases as well. But still i think this packages needs to be renamed https://github.com/accordproject/concerto/blob/master/packages/concerto-cli/package.json#L48

Yes this is absolutely correct, since that would be the dependency from `cicero-cli` to the new `cicero-core`. There should be a similar dependency in `cicero-tools`.

It is possible that there is a dependency to the package name in some of the tests for error messages. I can help figure that one out if need be. (a log for this if this happens would be helpful).

**Comment by Niladri24dutta** [comment]
> 
> 
> > > @Niladri24dutta you're exactly right, you should update the dependencies for `concerto-cli` and `concerto-tools` too. For example, https://github.com/accordproject/concerto/blob/master/packages/concerto-cli/package.json#L43
> > > @jeromesimeon this is a breaking change so we should bump to `0.81.0` on the next release.
> > 
> > 
> > @mttrbrts
> > Sure I will update the dependencies in `concerto-tools` package and others package.json if required. I was getting a strange issue in mocha during the test case execution so I updated the unit test cases as well. But still i think this packages needs to be renamed https://github.com/accordproject/concerto/blob/master/packages/concerto-cli/package.json#L48
> 
> Yes this is absolutely correct, since that would be the dependency from `cicero-cli` to the new `cicero-core`. There should be a similar dependency in `cicero-tools`.
> 
> It is possible that there is a dependency to the package name in some of the tests for error messages. I can help figure that one out if need be. (a log for this if this happens would be helpful).

Yeah I already fixed that it was in this commit https://github.com/accordproject/concerto/pull/75/commits/8f9c0fc73fdeffd3b319935672fae3db5510c49a#diff-4ffd2d6fd84fee54c94ed0ab58bca17cR21

**Comment by jeromesimeon** [comment]
> > Yes this is absolutely correct, since that would be the dependency from `cicero-cli` to the new `cicero-core`. There should be a similar dependency in `cicero-tools`.
> > It is possible that there is a dependency to the package name in some of the tests for error messages. I can help figure that one out if need be. (a log for this if this happens would be helpful).
> 
> Yeah I already fixed that it was in this commit
> [8f9c0fc](https://github.com/accordproject/concerto/commit/8f9c0fc73fdeffd3b319935672fae3db5510c49a)

That's the one! great 👍

**Comment by Niladri24dutta** [comment]
Hi @mttrbrts  and @jeromesimeon I have made the required changes as mentioned above and in this link https://github.com/accordproject/concerto/issues/74#issuecomment-537942799 . The build passed now. Let me know if any other change is require for this PR to be merged.

**Pull request merged**
