### PR TITLE
refactor: Use Globalize for error formatting

### LINKED ISSUE #838: Standardize/localize error messaging
# Feature Request 🛍️

Clean up error messages to use Globalization class to localize error messaging

### PR DESCRIPTION
**Pull request by AbhinRustagi**
# Closes #838

### Changes

- Added new error messages to be used by Globalize class
- Replace hard-coded error messages with usage of Globalize Class

### Related Issues
- Issue #<NUMBER>
- Pull Request #<NUMBER>

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `main` from `fork:branchname`

### CODE REVIEW

**Review by dselman — APPROVED** [review]
This is looking great. Thank you!

**Comment by AbhinRustagi** [comment]
Awesome, I'll update the rest of the files

**Comment by AbhinRustagi** [comment]
@dselman I see that there is no consistent way that the error message code has been crafted. In some cases, it is `filename-function-error_type`, in others it is `filename-error_type`. Which one do you think should be followed for consistency? I'd vote for the first kind.

**Comment by AbhinRustagi** [comment]
@dselman just following up

**Comment by dselman** [comment]
Your proposal works for me. 👌

**Pull request closed without merging**
