### PR TITLE
Minor Typo

### PR DESCRIPTION
**Pull request by AbhijithGanesh**
# Closes #<CORRESPONDING ISSUE NUMBER>

### Changes

- Changes typographic error

### Related Issues
- Issue #372 

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`

### CODE REVIEW

**Comment by AbhijithGanesh** [comment]
I shall sign it according to the standards

**Review by mttrbrts — APPROVED** [review]

**Comment by mttrbrts** [comment]
Good catch! There are some instructions here on how to fix the sign-off
https://github.com/accordproject/concerto/pull/373/checks?check_run_id=4798830007

**Comment by AbhijithGanesh** [comment]
I will sign it off well, I am new to the ecosystem but I'll catch up :)

**Comment by AbhijithGanesh** [comment]
The DCO has been taken care of.

**Comment by mttrbrts** [comment]
Thanks for the update @AbhijithGanesh. I'll merge it now. Although in future, please follow the guide here for rebasing. That helps to avoid conflicts with changes that happened since you last pulled down the code.
https://github.com/accordproject/techdocs/blob/master/CONTRIBUTING.md#-pull-request-submission-guidelines

**Pull request merged**
